spring.application.name=Reservoir New
server.port=${PORT:8080}

# Google Sheets API Configuration
#google.sheets.spreadsheet.id=${GOOGLE_SHEETS_ID:1AmOZLRT1yrb2bSOrHpCX3LI7fnLLxeJSnQmFhnY1nlo}
#google.sheets.spreadsheet.id=1AmOZLRT1yrb2bSOrHpCX3LI7fnLLxeJSnQmFhnY1nlo
google.sheets.spreadsheet.id=1-DYt34vz-nY9ebWnYeA7Rsls53jUS1JjAm6LTPwxSIg
google.sheets.credentials.path=${GOOGLE_CREDENTIALS_PATH:credentials.json}
# Name of the tab inside the spreadsheet that each day's sheet is cloned from
google.sheets.master.template.name=Master Template

# Logging Configuration
logging.level.root=INFO
logging.level.com.reservoir=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG

#https://docs.google.com/spreadsheets/d/1AmOZLRT1yrb2bSOrHpCX3LI7fnLLxeJSnQmFhnY1nlo/edit?usp=drive_link